  SELECT dba.oe_items_abonos_fac_cuotas.id_empresa,   
         dba.oe_items_abonos_fac_cuotas.id_documento,   
         dba.oe_items_abonos_fac_cuotas.num_documento,   
         dba.oe_items_abonos_fac_cuotas.tipo_doc_cobrar,   
         dba.oe_items_abonos_fac_cuotas.num_doc_cobrar,   
         dba.oe_items_abonos_fac_cuotas.num_cuota,   
         dba.oe_items_abonos_fac_cuotas.id_forma_pago,   
         dba.oe_items_abonos_fac_cuotas.id_medio_pago,   
         dba.oe_items_abonos_fac_cuotas.valor_total,   
         dba.oe_items_abonos_fac_cuotas.valor_efectivo,   
         dba.oe_items_abonos_fac_cuotas.valor_cheque,   
         dba.oe_items_abonos_fac_cuotas.num_cheque,   
         dba.oe_items_abonos_fac_cuotas.num_cuenta_cheque,   
         dba.oe_items_abonos_fac_cuotas.id_banco_cheque,   
         dba.oe_items_abonos_fac_cuotas.fec_cheque,   
         dba.oe_items_abonos_fac_cuotas.ind_lin_mayor,   
         dba.oe_items_abonos_fac_cuotas.id_evento_fact,   
         dba.oe_items_abonos_fac_cuotas.ind_cancelacion_total,   
         dba.oe_items_abonos_fac_cuotas.valor_especie,   
         dba.oe_items_abonos_fac_cuotas.valor_consignacion,   
         dba.oe_items_abonos_fac_cuotas.fecha_doc_cobrar,   
         dba.oe_items_abonos_fac_cuotas.con_item,   
         dba.oe_items_abonos_fac_cuotas.saldo,   
         dba.oe_items_abonos_fac_cuotas.tipo_doc_abono,   
         dba.oe_items_abonos_fac_cuotas.num_doc_abono,   
         dba.oe_items_abonos_fac_cuotas.valor_anticipo,   
         dba.oe_items_abonos_fac_cuotas.item_anticipo,   
         dba.oe_items_abonos_fac_cuotas.ind_corregida,   
         dba.oe_items_abonos_fac_cuotas.num_doc_proveedor  
    FROM dba.oe_items_abonos_fac_cuotas  
   WHERE dba.oe_items_abonos_fac_cuotas.num_documento between  21732 and 21807   ;
